export const stack = [
    'HTML',
    'CSS',
    'JS',
    'React',
    'Nextjs',
    'GIT',
    'TypeScript',
    'Tailwind',
    'Styled-components',
    'TDD',
    'JIRA',
    'Firebase',
    'Context API',
    'Fetch',
    'Redux',
]